exe "set runtimepath+=" . expand(prefix) . "/plugs/ervandew/supertab"
exe "set runtimepath+=" . expand(prefix) . "/plugs/tpope/vim-endwise"
exe "set runtimepath+=" . expand(prefix) . "/plugs/junegunn/vim-easy-align"
exe "set runtimepath+=" . expand(prefix) . "/plugs/kien/ctrlp.vim"
exe "set runtimepath+=" . expand(prefix) . "/plugs/nvim-treesitter/nvim-treesitter"
exe "set runtimepath+=" . expand(prefix) . "/plugs/neovim/nvim-lspconfig"
exe "set runtimepath+=" . expand(prefix) . "/plugs/williamboman/nvim-lsp-installer"
exe "set runtimepath+=" . expand(prefix) . "/plugs/wfxr/minimap.vim"
